name: CI NetDevOps Portal Cautivo

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Levantar la aplicación con Docker Compose
        run: |
          docker compose up -d
          # Esperar unos segundos a que el contenedor de Express inicie correctamente
          sleep 5

      - name: Instalar dependencias de pruebas E2E
        working-directory: ./tests-e2e
        run: npm install

      - name: Instalar navegadores de Playwright
        working-directory: ./tests-e2e
        run: npx playwright install --with-deps

      - name: Ejecutar Pruebas E2E (Playwright)
        working-directory: ./tests-e2e
        run: npx playwright test

      - name: Instalar k6 (Pruebas de Carga)
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C047C0FA5A
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Ejecutar Pruebas de Carga (k6)
        run: k6 run tests-performance/load-test.js